// Contenu de test pour le spike Typst/Lulu — prose mémorielle fictive, écrite pour
// remplir un chapitre à taille réelle (pagination, justification, veuves/orphelines).
// Pas du contenu produit par Sonnet : rédigé à la main pour ce test de gabarit.
export const FRAGMENTS_TEST_CHAPITRE: string[] = [
  `La maison de mon enfance sentait la cire et le bois mouillé. On y entrait par une porte trop lourde pour mes bras de petite fille, et il fallait pousser de tout le corps, l'épaule en avant, pour qu'elle cède enfin dans un grincement que j'aurais reconnu entre mille. Ma grand-mère cirait le parquet du couloir chaque samedi matin, à genoux, un chiffon de laine à la main, et l'odeur restait accrochée aux murs jusqu'au mercredi suivant. Je me souviens du froid du carrelage de la cuisine sous mes pieds nus l'été, et de la chaleur presque brûlante du poêle à bois l'hiver, qu'il fallait approcher sans le toucher, sous peine d'une réprimande sèche. Personne ne m'expliquait pourquoi les choses étaient ainsi rangées, pourquoi le pain se coupait toujours contre la poitrine et jamais sur la table. C'était comme ça, un point c'est tout, et cette phrase revenait si souvent qu'elle avait fini par devenir un mur porteur de mon enfance.`,

  `Mon père ne parlait jamais de la guerre, sauf une fois, un soir de novembre où le vin avait dû desserrer quelque chose en lui. Il avait raconté un pont, quelque part dans l'Est, et le bruit que faisaient les bottes sur le bois gelé — un bruit qu'il imitait avec sa langue contre son palais, un claquement sec et régulier. Puis il s'était arrêté net, comme si la phrase suivante n'avait pas le droit d'exister, et il était allé se coucher sans un mot de plus. Je n'ai jamais osé lui redemander. Ce silence-là, je l'ai porté longtemps comme une question sans réponse, et ce n'est que bien après sa mort que j'ai compris qu'il ne s'agissait pas d'un secret qu'il me cachait, mais d'un poids qu'il n'arrivait tout simplement pas à déposer devant quelqu'un d'autre, même devant sa propre fille.

—

L'école du village n'avait qu'une seule salle pour tous les âges, et l'instituteur, monsieur Lavigne, savait faire réciter les tables de multiplication aux petits pendant qu'il corrigeait les dictées des grands, sans jamais perdre le fil des deux à la fois. Il avait une règle en bois qu'il ne levait presque jamais, mais dont la seule présence sur son bureau suffisait à calmer la classe entière. Je me revois à la fenêtre, distraite par les vaches du champ voisin, recevant sur la nuque le petit coup sec d'une craie lancée avec une précision que je soupçonne aujourd'hui d'avoir été entretenue par des années de pratique. On n'aurait jamais pu faire ça aujourd'hui, et pourtant je n'en garde aucune rancœur — seulement le souvenir d'un homme qui tenait à ce qu'on sache lire correctement, envers et contre notre dissipation.`,

  `Le jour de mon mariage, il pleuvait si fort que ma mère avait pleuré, persuadée que c'était mauvais signe. Moi je trouvais que la pluie donnait à tout un air de cinéma, les gouttes sur les vitres de la traction qui nous menait à la mairie, le parapluie noir que mon oncle tenait au-dessus de nous en courant sur le trottoir mouillé. Je n'avais pas peur, contrairement à ce qu'on m'avait dit que je devais ressentir. J'étais simplement pressée que la cérémonie commence, pressée de voir le visage de celui qui m'attendait, un visage que je connaissais par cœur mais qui, ce jour-là, m'a semblé différent — plus grave, plus adulte, comme si lui aussi sentait que quelque chose commençait vraiment. Le repas s'est étiré tard dans la soirée, on a dansé dans la grange chez ses parents, et à un moment, en levant les yeux entre deux valses, j'ai vu ma grand-mère qui pleurait aussi, mais de l'autre façon.`,

  `J'ai travaillé vingt-trois ans dans cette usine, et je pourrais encore aujourd'hui reconnaître les bras de chacune de mes collègues rien qu'au bruit qu'elles faisaient en actionnant leur machine. Le matin, on arrivait avant le jour en hiver, et la sirène de six heures nous faisait toutes sursauter de la même manière, chaque fois, comme si on ne s'y habituait jamais vraiment. Il y avait une solidarité épaisse entre nous, une façon de se couvrir mutuellement quand l'une avait pris du retard, de partager le café d'un thermos, de se raconter nos vies par bribes entre deux gestes répétitifs mille fois par jour. Quand l'usine a fermé, en 1987, on s'est retrouvées sur le parking, sans savoir quoi faire de nos mains ni de nos journées. Certaines ne s'en sont jamais vraiment remises. Moi j'ai eu de la chance, j'ai retrouvé un emploi à la mairie deux ans après, mais je n'ai plus jamais ressenti cette camaraderie-là, cette évidence d'appartenir à un groupe de femmes qui se comprenaient sans avoir besoin de s'expliquer.

—

Mon premier enfant est né un dimanche matin, dans la chambre du fond, parce qu'on n'avait pas eu le temps d'arriver jusqu'à la maternité de la ville. La sage-femme du village est arrivée en vélo, essoufflée, et j'ai encore dans l'oreille sa voix qui me disait de respirer plus lentement, comme si c'était aussi simple que ça. La douleur, je l'ai oubliée, ou plutôt je ne cherche plus à m'en souvenir précisément — ce qui reste, en revanche, c'est ce silence absolu qui a suivi son premier cri, cette seconde suspendue où plus rien d'autre n'existait dans la pièce que ce petit corps posé sur moi, encore couvert, encore chaud d'un endroit que je ne reverrais jamais.`,

  `Il y a eu cet été-là, celui de mes quinze ans, où on est partis camper au bord du lac avec la bande du quartier. On dormait sous une toile qui prenait l'eau au moindre orage, et pourtant je n'ai jamais autant ri de ma vie qu'allongée dans ce sac de couchage humide, à écouter les garçons se raconter des histoires de pêche de plus en plus improbables à mesure que la nuit avançait. C'est là que j'ai fumé ma première cigarette, en cachette derrière les tentes, en toussant si fort que j'ai cru que toute la colonie allait se réveiller. C'est là aussi que j'ai compris, sans qu'on me le dise, que l'enfance touchait à sa fin — pas d'un coup, mais comme une marée qui se retire lentement, laissant derrière elle des choses qu'on ne remarque qu'après coup, une fois le sable redevenu sec.`,

  `Ma mère cuisinait comme on prie, avec une concentration qui n'admettait aucune interruption. Le dimanche, la cuisine devenait un territoire qu'il valait mieux ne pas traverser sans raison. Elle préparait le pot-au-feu dès l'aube, et l'odeur montait dans toute la maison, s'infiltrait jusque dans les chambres à l'étage, se mêlait à celle du feu qu'on allumait dans la cheminée du salon pour la journée. Je n'ai jamais réussi à reproduire exactement son bouillon, malgré toutes les fois où je l'ai regardée faire, malgré le carnet où j'avais noté chaque étape. Il devait manquer quelque chose que les mots ne savaient pas transmettre — un geste, un instinct, une main qui savait quand arrêter sans avoir besoin de goûter. Aujourd'hui encore, quand je sens cette odeur particulière quelque part dans la rue, en passant devant une fenêtre ouverte, je m'arrête une seconde, malgré moi, comme si elle allait apparaître au coin de la rue.

—

Le service militaire m'a envoyé loin de chez moi pour la première fois, dans une caserne du Nord où le vent ne s'arrêtait jamais vraiment. Je n'avais jamais vu autant de garçons venus d'endroits si différents, avec des accents que je peinais à comprendre au début, des habitudes qui me semblaient étranges et qui, je l'ai su plus tard, devaient trouver les miennes tout aussi curieuses. On s'est liés d'une amitié rapide et rugueuse, celle qu'on tisse quand on partage l'inconfort et l'ennui en proportions égales. J'ai appris à repasser un col de chemise avec une rigueur que je n'avais jamais eue avant, et à me taire au bon moment devant un supérieur, deux compétences dont je ne soupçonnais pas qu'elles me serviraient toute ma vie professionnelle par la suite.`,

  `Le jour où mon père est mort, il faisait un soleil incongru, presque insultant. Je me souviens d'être sortie de l'hôpital et d'avoir été surprise, presque choquée, que la rue continue comme si de rien n'était — un boulanger qui sortait ses plateaux, un enfant à vélo, une femme qui riait au téléphone. J'aurais voulu que le monde s'arrête un instant, ne serait-ce qu'une minute, en signe de respect pour ce qui venait de se passer dans cette chambre du quatrième étage. Ça n'arrive jamais, ce genre de chose, et c'est peut-être ça le plus dur dans un deuil : découvrir que le monde entier continue de tourner exactement au même rythme, indifférent, alors qu'à l'intérieur de soi, tout vient de s'arrêter net.`,

  `Nous avons acheté cette maison avec presque rien, à une époque où les banques prêtaient encore sur la seule confiance qu'inspirait un homme qui se levait tôt. Il a fallu tout refaire, la toiture d'abord, puis l'électricité, puis la salle de bain qu'on a installée nous-mêmes avec l'aide d'un cousin plombier qui venait le dimanche pour presque rien, en échange d'un repas et d'un peu de vin. Je revois encore mon mari, un été entier, en sueur sur l'échafaudage improvisé, refusant obstinément l'aide de qui que ce soit d'autre pour la charpente, par une fierté que je trouvais parfois exaspérante et que je comprends mieux aujourd'hui. Cette maison, on l'a faite de nos mains, littéralement, pierre après pierre, et c'est peut-être pour ça que je n'ai jamais réussi à envisager d'en partir, même après tout ce qui s'y est passé, les bonheurs comme les chagrins.

—

Il y avait un arbre, un vieux tilleul, au fond du jardin de mes grands-parents, et l'été, toute la famille s'y retrouvait à l'ombre pour échapper à la chaleur du après-midi. Mon grand-père y installait une table pliante et des chaises dépareillées, et c'est là, sous cet arbre précisément, que j'ai appris à jouer aux cartes, que j'ai entendu pour la première fois l'histoire de comment mes grands-parents s'étaient rencontrés — un bal de village, une robe bleue, une maladresse de sa part qui avait fait rire toute la salle. Cet arbre a été abattu il y a bien longtemps, la maison vendue à des gens que je ne connais pas, mais il m'arrive encore de rêver de son ombre exacte sur l'herbe, de la texture particulière de son écorce contre mon dos quand je m'y adossais pour lire, l'après-midi, pendant que les adultes parlaient à voix basse de sujets qui, croyaient-ils, m'échappaient complètement.`,

  `Le premier salaire que j'ai touché de ma vie, je l'ai posé entier sur la table de la cuisine devant ma mère, sans en avoir dépensé un centime, simplement pour qu'elle voie que j'y étais arrivée. Elle a compté les billets deux fois, sans rien dire, puis elle m'en a rendu la moitié en me regardant droit dans les yeux, avec une fierté qu'elle n'exprimait presque jamais autrement que par ce genre de geste. Je n'ai jamais oublié cette scène, ni la sensation d'être devenue, l'espace d'un instant, quelqu'un qui contribue, quelqu'un qu'on ne nourrit plus seulement par charité mais avec qui l'on partage désormais quelque chose d'égal à égal.`,

  `On ne parlait pas de sentiments, dans notre famille, on les montrait autrement — un plat préparé sans qu'on l'ait demandé, une place gardée au chaud près du poêle, un silence partagé sans gêne un dimanche après-midi de pluie. Ce n'est que très tard, presque à la fin de sa vie, que ma mère m'a dit pour la première fois qu'elle m'aimait, avec ces mots-là précisément, et j'ai été si surprise que j'ai mis plusieurs secondes à lui répondre. Je crois qu'elle aussi en a été troublée, d'avoir dit tout haut ce qui n'avait jamais eu besoin d'être formulé entre nous pour exister. Depuis, je me suis fait la promesse de le dire à mes propres enfants plus souvent, même quand ça me semble étrange ou trop direct, parce que je sais désormais combien ce silence, aussi tendre soit-il, peut aussi laisser un vide.

—

Le vélo de mon enfance était trop grand pour moi, hérité d'un cousin, repeint en bleu par mon père pour que je ne me plaigne pas trop de sa provenance. Je suis tombée si souvent la première année que mes genoux ont gardé des cicatrices dont on distingue encore la trace aujourd'hui, en été, quand la peau bronze autour. C'est sur ce vélo trop grand que j'ai appris la liberté, la vraie, celle de partir seule jusqu'au bout du chemin sans que personne ne me surveille, de sentir le vent contre mon visage à une vitesse qui me semblait, à l'époque, absolument vertigineuse.`,

  `Le pays où j'ai grandi n'existe presque plus tel que je l'ai connu — les champs sont devenus des lotissements, l'épicerie a fermé, le café du village s'est transformé en agence immobilière. Quand j'y retourne, ce qui m'arrive de moins en moins souvent, je marche dans des rues qui portent les mêmes noms mais qui ne ressemblent en rien à mes souvenirs. Je pourrais m'en attrister, et parfois je le fais, mais je préfère penser que ce village-là continue d'exister quelque part, intact, dans cette mémoire précise que je m'apprête à raconter — et que c'est peut-être bien pour ça que je fais cet effort aujourd'hui, pour qu'il ne disparaisse pas complètement avec moi.`,

  `Je me souviens du jour où j'ai su lire, vraiment lire, sans plus déchiffrer syllabe après syllabe mais en comprenant le sens d'une phrase entière d'un seul regard. C'était un livre sur les animaux d'Afrique, emprunté à la bibliothèque municipale, et j'ai lu la même page trois fois de suite tellement j'étais fière de moi. À partir de ce jour, je n'ai plus jamais arrêté. Les livres sont devenus une façon d'être ailleurs sans quitter ma chambre, une échappatoire dont je n'ai jamais eu honte, contrairement à ce que certains semblaient penser d'une fille "qui avait toujours le nez dans un bouquin". Je le revendiquais, ce nez dans le bouquin, comme une part essentielle de qui j'étais, et je le revendique encore aujourd'hui.

—

La dernière fois que j'ai vu ma sœur avant qu'elle ne parte vivre au Canada, on s'est disputées pour une broutille, quelque chose de si insignifiant que je serais bien incapable de m'en souvenir aujourd'hui. Elle est partie fâchée, et ce n'est que des mois plus tard, par une lettre, que nous avons fait la paix, chacune de notre côté de l'Atlantique. Je regrette encore cette dernière soirée gâchée pour rien, cette occasion manquée de lui dire au revoir comme il l'aurait fallu. On ne sait jamais, sur le moment, laquelle de nos disputes sera la dernière avant un départ, et c'est peut-être la leçon la plus dure que la vie m'ait enseignée : ne jamais laisser une colère avoir le dernier mot avec ceux qu'on aime.`,
];
